name: Create Release

on:
  push:
    tags:
      - "dbt-dataops-*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: version
        id: version
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          version=${tag#v}
          major=${version%%.*}
          echo "::set-output name=tag::${tag}"
          echo "::set-output name=version::${version}"
          echo "::set-output name=major::${major}"
          echo "${tag}"
          echo "${version}"
          echo "${major}"
      - uses: release-drafter/release-drafter@master
        with:
          version: ${{ steps.version.outputs.version }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
